- name: Certbot および Apache プラグインのインストール
  yum:
    name: certbot-apache
    state: present

- name: Let’s Encrypt 証明書の取得または更新
  command: >-
    certbot --apache -n --agree-tos
            -m admin@{{ domain_name }}
            -d {{ domain_name }}
            --redirect
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
  notify: reload httpd

- name: /etc/cron.d ディレクトリが存在することを確認
  file:
    path: /etc/cron.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Certbot 自動更新用の cron ジョブを追加
  copy:
    dest: /etc/cron.d/certbot-renew
    content: |
      0 3 * * * root certbot renew --quiet
    owner: root
    group: root
    mode: '0644'

