- name: GoAccess の tar.gz をダウンロード
  get_url:
    url: https://tar.goaccess.io/goaccess-1.7.2.tar.gz
    dest: /tmp/goaccess-1.7.2.tar.gz

- name: ビルドに必要なパッケージをインストール
  dnf:
    name:
      - gcc
      - make
      - autoconf
      - automake
      - ncurses-devel
      - zlib-devel
    state: present

- name: GoAccess ソースを解凍
  unarchive:
    src: /tmp/goaccess-1.7.2.tar.gz
    dest: /tmp/
    remote_src: yes

- name: GoAccess を configure
  command: ./configure --enable-utf8
  args:
    chdir: /tmp/goaccess-1.7.2

- name: GoAccess を make
  command: make
  args:
    chdir: /tmp/goaccess-1.7.2

- name: GoAccess を make install
  command: make install
  become: true
  args:
    chdir: /tmp/goaccess-1.7.2


